# Plotting

In [1]:
from blokk_solver.blokks import blokks
blokks

id      name               color  volume  \
0    1  Block 01   rgb(239, 139, 27)       1   
1    2  Block 02   rgb(106, 194, 84)       2   
2    3  Block 03  rgb(244, 195, 203)       3   
3    4  Block 04   rgb(252, 221, 80)       3   
4    5  Block 05         purple-blue       4   
5    6  Block 06   rgb(239, 139, 27)       4   
6    7  Block 07   rgb(239, 139, 27)       4   
7    8  Block 08   rgb(239, 139, 27)       4   
8    9  Block 09   rgb(252, 221, 80)       4   
9   10  Block 10  rgb(244, 195, 203)       4   
10  11  Block 11   rgb(239, 139, 27)       4   
11  12  Block 12   rgb(106, 194, 84)       5   
12  13  Block 13   rgb(252, 221, 80)       5   
13  14  Block 14   rgb(239, 139, 27)       5   
14  15  Block 15   rgb(252, 221, 80)       5   
15  16  Block 16   rgb(106, 194, 84)       5   
16  17  Block 17   rgb(106, 194, 84)       5   
17  18  Block 18  rgb(244, 195, 203)       5   
18  19  Block 19  rgb(244, 195, 203)       5   
19  20  Block 20   rgb(106, 194, 84)       5   
20  21  Block 21   rgb(106, 194, 84)       5   
21  22  Block 22   rgb(252, 221, 80)       5   
22  23  Block 23   rgb(239, 139, 27)       5   
23  24  Block 24   rgb(252, 221, 80)       5   
24  25  Block 25  rgb(244, 195, 203)       5   
25  26  Block 26  rgb(244, 195, 203)       5   
26  27  Block 27   rgb(87, 194, 230)       5   
27  28  Block 28   rgb(167, 99, 137)       5   
28  29  Block 29   rgb(87, 194, 230)       5   
29  30  Block 30   rgb(167, 99, 137)       5   
30  31  Block 31   rgb(87, 194, 230)       5   
31  32  Block 32   rgb(167, 99, 137)       5   
32  33  Block 33   rgb(87, 194, 230)       5   
33  34  Block 34   rgb(167, 99, 137)       5   
34  35  Block 35   rgb(87, 194, 230)       5   
35  36  Block 36   rgb(167, 99, 137)       5   

                                                shape  max_length  
0                                         [[0, 0, 0]]           1  
1                              [[0, 0, 0], [1, 0, 0]]           2  
2                   [[0, 0, 0], [1, 0, 0], [2, 0, 0]]           3  
3                   [[0, 0, 0], [0, 1, 0], [0, 2, 0]]           3  
4        [[0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0]]           3  
5        [[0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0]]           3  
6        [[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 2, 0]]           3  
7        [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 0, 0]]           3  
8        [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0]]           3  
9        [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 2, 0]]           3  
10       [[0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 0, 0]]           3  
11  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [...           3  
12  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [...           4  
13  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 0], [...           3  
14  [[0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0], [...           3  
15  [[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 2, 0], [...           3  
16  [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 2, 0], [...           3  
17  [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 1, 0], [...           3  
18  [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 0, 0], [...           3  
19  [[0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0], [...           3  
20  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [...           3  
21  [[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 2, 0], [...           3  
22  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 0], [...           3  
23  [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 1, 0], [...           3  
24  [[0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0], [...           3  
25  [[0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [...           3  
26  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [...           4  
27  [[0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [...           3  
28  [[0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [...           3  
29  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 0], [...           3  
30  [[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 2, 0], [...           3  
31  [[0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [.

# Visualizing

In [4]:
from blokk_solver.combinatorics import generate_rotations, generate_translations
from blokk_solver.plotting import plot_voxels
import plotly.graph_objects as go

import numpy as np

In [5]:
import plotly.colors
palette = plotly.colors.qualitative.Plotly

sample_shape = [[0,0,0], [0,1,0]]

rotations = generate_rotations(voxels=sample_shape)
translations = generate_translations(voxels=rotations[0], n=2)
print(f"""
sample_shape = 
{np.array(sample_shape)}
first rotation =
{np.array(rotations[0])}
first translation of first rotation =
{np.array(translations[0])}
""")
fig = go.Figure()
plot_voxels(voxels=rotations[0], fig=fig, n=2, color=palette[0])
plot_voxels(voxels=rotations[1], fig=fig, n=2, color=palette[1])
fig.show()

fig = go.Figure()
print(f"""
plotting all {len(translations)} translations
{translations}
""")
for idx,t in enumerate(translations):
    fig = plot_voxels(voxels=t, fig=fig, n=2, color=palette[idx], opacity=1)
fig.show()


sample_shape = 
[[0 0 0]
 [0 1 0]]
first rotation =
[[0 0 0]
 [0 0 1]]
first translation of first rotation =
[[0 0 0]
 [0 0 1]]




plotting all 4 translations
[[[0 0 0]
  [0 0 1]]

 [[0 1 0]
  [0 1 1]]

 [[1 0 0]
  [1 0 1]]

 [[1 1 0]
  [1 1 1]]]



# Generating all

In [2]:
from blokk_solver.blokks import get_blokks
from blokk_solver.combinatorics import generate_rotations, generate_translations, generate_all_placements
from blokk_solver.plotting import plot_voxels
import plotly.graph_objects as go
import numpy as np

blokks = get_blokks()

blokks['all_rotations'] = blokks['voxels'].apply(np.array).apply(generate_rotations).apply(np.array)  # a list of blokks
blokks['n_rotations'] = blokks['all_rotations'].apply(lambda x: len(x))

blokks['all_placements_3'] = blokks['voxels'].iloc[[12]].apply(generate_all_placements, n=3)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 1 dimension(s)

In [6]:
plot_voxels(blokks.loc[12, "voxels"])

In [2]:
blokks['all_placements_3']

id
1     [[[0, 0, 0]], [[0, 0, 1]], [[0, 0, 2]], [[0, 1...
2     [[[0, 0, 0], [0, 0, 1]], [[0, 0, 0], [0, 1, 0]...
3     [[[0, 0, 0], [0, 0, 1], [0, 0, 2]], [[0, 0, 0]...
4     [[[0, 0, 0], [0, 0, 1], [0, 0, 2]], [[0, 0, 0]...
5     [[[0, 0, 0], [0, 0, 1], [0, 1, 1], [0, 1, 2]],...
6                                                   NaN
7                                                   NaN
8                                                   NaN
9                                                   NaN
10                                                  NaN
11                                                  NaN
12                                                  NaN
13                                                  NaN
14                                                  NaN
15                                                  NaN
16                                                  NaN
17                                                  NaN
18                                           

In [11]:

example_shape = blokks.loc[12, "voxels"]  # id=2
example_n = 3
fig = plot_voxels(voxels=example_shape, n=example_n, color="black")
fig.show()

# there should be 54 unique placements of id=2 in a 3x3 game!
# id=12, the L shaped one, introduces a problem in 3x3 but not 4x4 ---

all_rotations = generate_rotations(voxels=example_shape)
all_placements = generate_all_placements(voxels=example_shape, n=example_n)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 1 dimension(s)

In [12]:
import plotly.graph_objects as go
import plotly.colors
palette = plotly.colors.qualitative.Plotly

fig = go.Figure()
for idx,p in enumerate(all_rotations[:6]):
    plot_voxels(voxels=p, fig=fig, n=example_n, color=palette[idx], opacity=0.9)
fig.show()


In [13]:
(((4 * 4) * 3) * 3)

144