# Plotting

In [1]:
from blokk_solver.blokks import blokks
blokks

id      name               color  volume  \
0    1  Block 01   rgb(239, 139, 27)       1   
1    2  Block 02   rgb(106, 194, 84)       2   
2    3  Block 03  rgb(244, 195, 203)       3   
3    4  Block 04   rgb(252, 221, 80)       3   
4    5  Block 05         purple-blue       4   
5    6  Block 06   rgb(239, 139, 27)       4   
6    7  Block 07   rgb(239, 139, 27)       4   
7    8  Block 08   rgb(239, 139, 27)       4   
8    9  Block 09   rgb(252, 221, 80)       4   
9   10  Block 10  rgb(244, 195, 203)       4   
10  11  Block 11   rgb(239, 139, 27)       4   
11  12  Block 12   rgb(106, 194, 84)       5   
12  13  Block 13   rgb(252, 221, 80)       5   
13  14  Block 14   rgb(239, 139, 27)       5   
14  15  Block 15   rgb(252, 221, 80)       5   
15  16  Block 16   rgb(106, 194, 84)       5   
16  17  Block 17   rgb(106, 194, 84)       5   
17  18  Block 18  rgb(244, 195, 203)       5   
18  19  Block 19  rgb(244, 195, 203)       5   
19  20  Block 20   rgb(106, 194, 84)       5   
20  21  Block 21   rgb(106, 194, 84)       5   
21  22  Block 22   rgb(252, 221, 80)       5   
22  23  Block 23   rgb(239, 139, 27)       5   
23  24  Block 24   rgb(252, 221, 80)       5   
24  25  Block 25  rgb(244, 195, 203)       5   
25  26  Block 26  rgb(244, 195, 203)       5   
26  27  Block 27   rgb(87, 194, 230)       5   
27  28  Block 28   rgb(167, 99, 137)       5   
28  29  Block 29   rgb(87, 194, 230)       5   
29  30  Block 30   rgb(167, 99, 137)       5   
30  31  Block 31   rgb(87, 194, 230)       5   
31  32  Block 32   rgb(167, 99, 137)       5   
32  33  Block 33   rgb(87, 194, 230)       5   
33  34  Block 34   rgb(167, 99, 137)       5   
34  35  Block 35   rgb(87, 194, 230)       5   
35  36  Block 36   rgb(167, 99, 137)       5   

                                                shape  max_length  
0                                         [[0, 0, 0]]           1  
1                              [[0, 0, 0], [1, 0, 0]]           2  
2                   [[0, 0, 0], [1, 0, 0], [2, 0, 0]]           3  
3                   [[0, 0, 0], [0, 1, 0], [0, 2, 0]]           3  
4        [[0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0]]           3  
5        [[0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0]]           3  
6        [[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 2, 0]]           3  
7        [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 0, 0]]           3  
8        [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0]]           3  
9        [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 2, 0]]           3  
10       [[0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 0, 0]]           3  
11  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [...           3  
12  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [...           4  
13  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 0], [...           3  
14  [[0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0], [...           3  
15  [[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 2, 0], [...           3  
16  [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 2, 0], [...           3  
17  [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 1, 0], [...           3  
18  [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 0, 0], [...           3  
19  [[0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0], [...           3  
20  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [...           3  
21  [[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 2, 0], [...           3  
22  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 0], [...           3  
23  [[0, 0, 0], [0, 1, 0], [0, 2, 0], [1, 1, 0], [...           3  
24  [[0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 2, 0], [...           3  
25  [[0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [...           3  
26  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [...           4  
27  [[0, 0, 0], [0, 1, 0], [1, 1, 0], [2, 1, 0], [...           3  
28  [[0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [...           3  
29  [[0, 0, 0], [1, 0, 0], [2, 0, 0], [1, 1, 0], [...           3  
30  [[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 2, 0], [...           3  
31  [[0, 0, 0], [1, 0, 0], [1, 1, 0], [2, 1, 0], [.

In [2]:
import plotly.graph_objects as go
from numpy.typing import ArrayLike

def plot_blokk_shape_plotly(voxels: list[ArrayLike], color=None, n=3, fig=None, show_coord_markers=False, cube_size=0.92):
    xs, ys, zs = zip(*voxels)
    if(fig is None):
        fig = go.Figure()
    
    if show_coord_markers:
        fig.add_trace(go.Scatter3d(
            x=xs, y=ys, z=zs,
            mode='markers',
            marker=dict(size=10, color=color, opacity=0.8, line=dict(width=2, color='black'))
        ))
    
    offset = (1 - cube_size) / 2
    # Draw cubes for each block
    for x, y, z in voxels:
        fig.add_trace(go.Mesh3d(
            x=[x+offset, x+cube_size+offset, x+cube_size+offset, x+offset, x+offset, x+cube_size+offset, x+cube_size+offset, x+offset],
            y=[y+offset, y+offset, y+cube_size+offset, y+cube_size+offset, y+offset, y+offset, y+cube_size+offset, y+cube_size+offset],
            z=[z+offset, z+offset, z+offset, z+offset, z+cube_size+offset, z+cube_size+offset, z+cube_size+offset, z+cube_size+offset],
            color=color,
            opacity=0.5,
            alphahull=1,
            showscale=False
        ))
    # Optionally, draw the bounding cube (transparent)
    fig.add_trace(go.Mesh3d(
        x=[0, n, n, 0, 0, n, n, 0],
        y=[0, 0, n, n, 0, 0, n, n],
        z=[0, 0, 0, 0, n, n, n, n],
        color='lightgray',
        opacity=0.1,
        alphahull=0,
        showscale=False
    ))
    fig.update_layout(
        scene=dict(
            xaxis_title='X',
            yaxis_title='Y',
            zaxis_title='Z',
            aspectratio=dict(x=1, y=1, z=1),
            xaxis=dict(range=[0, n]),
            yaxis=dict(range=[0, n]),
            zaxis=dict(range=[0, n]),
        ),
        margin=dict(l=0, r=0, b=0, t=0)
    )
    return fig

# Prototyping

In [6]:
from blokk_solver.combinatorics import generate_rotations, generate_translations
import numpy as np

In [7]:
sample_shape = [[0,0,0], [0,1,0]]
plot_blokk_shape_plotly(voxels=sample_shape, n=2)

In [8]:
rotations = generate_rotations(voxels=sample_shape)
translations = generate_translations(voxels=sample_shape, n=2)
print(f"""
sample_shape = 
{np.array(sample_shape)}
first translation =
{np.array(translations[0])}
first rotation =
{np.array(rotations[0])}
""")
plot_blokk_shape_plotly(voxels=rotations[-1], n=2)


sample_shape = 
[[0 0 0]
 [0 1 0]]
first translation =
[[0 0 0]
 [0 1 0]]
first rotation =
[[0 0 0]
 [0 0 1]]



In [9]:
translations = generate_translations(voxels=sample_shape, n=2)
fig = go.Figure()
print(len(translations))
for t in translations:
    plot_blokk_shape_plotly(voxels=t, fig=fig, color='black', n=2)
fig.show()

4


In [ ]:
generate_rotations(voxels=[[0,0,0], [0,0,1]])

In [ ]:
l = generate_rotations(voxels=[[0,0,0], [0,0,1]])
s = np.unique(l, axis=0)
print(f"list len = {len(l)}, set len = {len(s)}")

In [ ]:
from ipywidgets import widgets
from IPython.display import display

import plotly.graph_objects as go

# Generate all rotations for the test_shape
rotations = list(generate_rotations(test_shape, n))[:10]

def plot_rotation(idx):
    shape = rotations[idx]
    fig = plot_blokk_shape_plotly(shape=shape, color='orange', n=n, show_coord_markers=True)
    fig.update_layout(title_text=f"Rotation {idx+1}/{len(rotations)}")
    fig.show()

slider = widgets.IntSlider(min=0, max=len(rotations)-1, step=1, value=0, description='Rotation')
widgets.interact(plot_rotation, idx=slider)

In [ ]:
all_placements[2]

In [ ]:
fig = go.Figure()
for p in all_placements[3]:
    plot_blokk_shape_plotly(shape=p, fig=fig, color=None, n=3, show_coord_markers=True)
fig.show()

In [ ]:
shape_to_game_board(shape = all_placements[0], n=5)